/**
 * Copyright � 2015, Thomas Schreiner, thomas1.schreiner@googlemail.com
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * The views and conclusions contained in the software and documentation are those
 * of the authors and should not be interpreted as representing official policies,
 * either expressed or implied, of the FreeBSD Project.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.01 at 12:27:25 PM CET 
//


package de.radiohacks.frinmeba.modellong;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.radiohacks.frinmeba.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.radiohacks.frinmeba.model
     * 
     */
    public ObjectFactory() {
    	super();
    }

    /**
     * Create an instance of {@link OutListUser }
     * 
     */
    public OutListUser createOutListUser() {
        return new OutListUser();
    }

    /**
     * Create an instance of {@link OutListChat }
     * 
     */
    public OutListChat createOutListChat() {
        return new OutListChat();
    }

    /**
     * Create an instance of {@link OutCheckNewMessages }
     * 
     */
    public OutCheckNewMessages createOutCheckNewMessages() {
        return new OutCheckNewMessages();
    }

    /**
     * Create an instance of {@link OutFetchMessageFromChat }
     * 
     */
    public OutFetchMessageFromChat createOutFetchMessageFromChat() {
        return new OutFetchMessageFromChat();
    }

    /**
     * Create an instance of {@link InSendLocationMessage }
     * 
     */
    public InSendLocationMessage createInSendLocationMessage() {
        return new InSendLocationMessage();
    }

    /**
     * Create an instance of {@link OutFetchLocationMessage }
     * 
     */
    public OutFetchLocationMessage createOutFetchLocationMessage() {
        return new OutFetchLocationMessage();
    }

    /**
     * Create an instance of {@link OutFetchMessageFromChat.Message }
     * 
     */
    public OutFetchMessageFromChat.Message createOutFetchMessageFromChatMessage() {
        return new OutFetchMessageFromChat.Message();
    }

    /**
     * Create an instance of {@link OutListChat.Chat }
     * 
     */
    public OutListChat.Chat createOutListChatChat() {
        return new OutListChat.Chat();
    }

    /**
     * Create an instance of {@link InInsertMessageIntoChat }
     * 
     */
    public InInsertMessageIntoChat createInInsertMessageIntoChat() {
        return new InInsertMessageIntoChat();
    }

    /**
     * Create an instance of {@link InListUser }
     * 
     */
    public InListUser createInListUser() {
        return new InListUser();
    }

    /**
     * Create an instance of {@link OutSendLocationMessage }
     * 
     */
    public OutSendLocationMessage createOutSendLocationMessage() {
        return new OutSendLocationMessage();
    }

    /**
     * Create an instance of {@link OutSendVideoMessage }
     * 
     */
    public OutSendVideoMessage createOutSendVideoMessage() {
        return new OutSendVideoMessage();
    }

    /**
     * Create an instance of {@link InFetchImageMessage }
     * 
     */
    public InFetchImageMessage createInFetchImageMessage() {
        return new InFetchImageMessage();
    }

    /**
     * Create an instance of {@link InFetchMessageFromChat }
     * 
     */
    public InFetchMessageFromChat createInFetchMessageFromChat() {
        return new InFetchMessageFromChat();
    }

    /**
     * Create an instance of {@link InSignup }
     * 
     */
    public InSignup createInSignup() {
        return new InSignup();
    }

    /**
     * Create an instance of {@link InGetVideoMessageMetaData }
     * 
     */
    public InGetVideoMessageMetaData createInGetVideoMessageMetaData() {
        return new InGetVideoMessageMetaData();
    }

    /**
     * Create an instance of {@link InCheckNewMessages }
     * 
     */
    public InCheckNewMessages createInCheckNewMessages() {
        return new InCheckNewMessages();
    }

    /**
     * Create an instance of {@link InGetFileMessageMetaData }
     * 
     */
    public InGetFileMessageMetaData createInGetFileMessageMetaData() {
        return new InGetFileMessageMetaData();
    }

    /**
     * Create an instance of {@link OutGetVideoMessageMetaData }
     * 
     */
    public OutGetVideoMessageMetaData createOutGetVideoMessageMetaData() {
        return new OutGetVideoMessageMetaData();
    }

    /**
     * Create an instance of {@link OutListUser.User }
     * 
     */
    public OutListUser.User createOutListUserUser() {
        return new OutListUser.User();
    }

    /**
     * Create an instance of {@link InSendContactMessage }
     * 
     */
    public InSendContactMessage createInSendContactMessage() {
        return new InSendContactMessage();
    }

    /**
     * Create an instance of {@link InFetchVideoMessage }
     * 
     */
    public InFetchVideoMessage createInFetchVideoMessage() {
        return new InFetchVideoMessage();
    }

    /**
     * Create an instance of {@link OutAddUserToChat }
     * 
     */
    public OutAddUserToChat createOutAddUserToChat() {
        return new OutAddUserToChat();
    }

    /**
     * Create an instance of {@link InSendFileMessage }
     * 
     */
    public InSendFileMessage createInSendFileMessage() {
        return new InSendFileMessage();
    }

    /**
     * Create an instance of {@link InDeleteChat }
     * 
     */
    public InDeleteChat createInDeleteChat() {
        return new InDeleteChat();
    }

    /**
     * Create an instance of {@link InDeleteMessageFromChat }
     * 
     */
    public InDeleteMessageFromChat createInDeleteMessageFromChat() {
        return new InDeleteMessageFromChat();
    }

    /**
     * Create an instance of {@link OutFetchTextMessage }
     * 
     */
    public OutFetchTextMessage createOutFetchTextMessage() {
        return new OutFetchTextMessage();
    }

    /**
     * Create an instance of {@link InSendTextMessage }
     * 
     */
    public InSendTextMessage createInSendTextMessage() {
        return new InSendTextMessage();
    }

    /**
     * Create an instance of {@link InFetchContactMessage }
     * 
     */
    public InFetchContactMessage createInFetchContactMessage() {
        return new InFetchContactMessage();
    }

    /**
     * Create an instance of {@link InAddUserToChat }
     * 
     */
    public InAddUserToChat createInAddUserToChat() {
        return new InAddUserToChat();
    }

    /**
     * Create an instance of {@link InCreateChat }
     * 
     */
    public InCreateChat createInCreateChat() {
        return new InCreateChat();
    }

    /**
     * Create an instance of {@link OutRemoveUserFromChat }
     * 
     */
    public OutRemoveUserFromChat createOutRemoveUserFromChat() {
        return new OutRemoveUserFromChat();
    }

    /**
     * Create an instance of {@link InSendImageMessage }
     * 
     */
    public InSendImageMessage createInSendImageMessage() {
        return new InSendImageMessage();
    }

    /**
     * Create an instance of {@link OutCheckNewMessages.Chats }
     * 
     */
    public OutCheckNewMessages.Chats createOutCheckNewMessagesChats() {
        return new OutCheckNewMessages.Chats();
    }

    /**
     * Create an instance of {@link OutCreateChat }
     * 
     */
    public OutCreateChat createOutCreateChat() {
        return new OutCreateChat();
    }

    /**
     * Create an instance of {@link OutFetchContactMessage }
     * 
     */
    public OutFetchContactMessage createOutFetchContactMessage() {
        return new OutFetchContactMessage();
    }

    /**
     * Create an instance of {@link OutFetchFileMessage }
     * 
     */
    public OutFetchFileMessage createOutFetchFileMessage() {
        return new OutFetchFileMessage();
    }

    /**
     * Create an instance of {@link InGetImageMessageMetaData }
     * 
     */
    public InGetImageMessageMetaData createInGetImageMessageMetaData() {
        return new InGetImageMessageMetaData();
    }

    /**
     * Create an instance of {@link InFetchTextMessage }
     * 
     */
    public InFetchTextMessage createInFetchTextMessage() {
        return new InFetchTextMessage();
    }

    /**
     * Create an instance of {@link InSendVideoMessage }
     * 
     */
    public InSendVideoMessage createInSendVideoMessage() {
        return new InSendVideoMessage();
    }

    /**
     * Create an instance of {@link OutAuthenticate }
     * 
     */
    public OutAuthenticate createOutAuthenticate() {
        return new OutAuthenticate();
    }

    /**
     * Create an instance of {@link OutGetFileMessageMetaData }
     * 
     */
    public OutGetFileMessageMetaData createOutGetFileMessageMetaData() {
        return new OutGetFileMessageMetaData();
    }

    /**
     * Create an instance of {@link OutInsertMessageIntoChat }
     * 
     */
    public OutInsertMessageIntoChat createOutInsertMessageIntoChat() {
        return new OutInsertMessageIntoChat();
    }

    /**
     * Create an instance of {@link OutSendImageMessage }
     * 
     */
    public OutSendImageMessage createOutSendImageMessage() {
        return new OutSendImageMessage();
    }

    /**
     * Create an instance of {@link InAuthenticate }
     * 
     */
    public InAuthenticate createInAuthenticate() {
        return new InAuthenticate();
    }

    /**
     * Create an instance of {@link OutSendFileMessage }
     * 
     */
    public OutSendFileMessage createOutSendFileMessage() {
        return new OutSendFileMessage();
    }

    /**
     * Create an instance of {@link OutFetchVideoMessage }
     * 
     */
    public OutFetchVideoMessage createOutFetchVideoMessage() {
        return new OutFetchVideoMessage();
    }

    /**
     * Create an instance of {@link InFetchFileMessage }
     * 
     */
    public InFetchFileMessage createInFetchFileMessage() {
        return new InFetchFileMessage();
    }

    /**
     * Create an instance of {@link OutSendTextMessage }
     * 
     */
    public OutSendTextMessage createOutSendTextMessage() {
        return new OutSendTextMessage();
    }

    /**
     * Create an instance of {@link OutSignUp }
     * 
     */
    public OutSignUp createOutSignUp() {
        return new OutSignUp();
    }

    /**
     * Create an instance of {@link InSendLocationMessage.LocationMessage }
     * 
     */
    public InSendLocationMessage.LocationMessage createInSendLocationMessageLocationMessage() {
        return new InSendLocationMessage.LocationMessage();
    }

    /**
     * Create an instance of {@link OutDeleteChat }
     * 
     */
    public OutDeleteChat createOutDeleteChat() {
        return new OutDeleteChat();
    }

    /**
     * Create an instance of {@link InListChat }
     * 
     */
    public InListChat createInListChat() {
        return new InListChat();
    }

    /**
     * Create an instance of {@link InRemoveUserFromChat }
     * 
     */
    public InRemoveUserFromChat createInRemoveUserFromChat() {
        return new InRemoveUserFromChat();
    }

    /**
     * Create an instance of {@link OutSendContactMessage }
     * 
     */
    public OutSendContactMessage createOutSendContactMessage() {
        return new OutSendContactMessage();
    }

    /**
     * Create an instance of {@link OutFetchLocationMessage.LocationMessage }
     * 
     */
    public OutFetchLocationMessage.LocationMessage createOutFetchLocationMessageLocationMessage() {
        return new OutFetchLocationMessage.LocationMessage();
    }

    /**
     * Create an instance of {@link OutDeleteMessageFromChat }
     * 
     */
    public OutDeleteMessageFromChat createOutDeleteMessageFromChat() {
        return new OutDeleteMessageFromChat();
    }

    /**
     * Create an instance of {@link InFetchLocationMessage }
     * 
     */
    public InFetchLocationMessage createInFetchLocationMessage() {
        return new InFetchLocationMessage();
    }

    /**
     * Create an instance of {@link OutGetImageMessageMetaData }
     * 
     */
    public OutGetImageMessageMetaData createOutGetImageMessageMetaData() {
        return new OutGetImageMessageMetaData();
    }

    /**
     * Create an instance of {@link OutFetchImageMessage }
     * 
     */
    public OutFetchImageMessage createOutFetchImageMessage() {
        return new OutFetchImageMessage();
    }

    /**
     * Create an instance of {@link OutFetchMessageFromChat.Message.OwningUser }
     * 
     */
    public OutFetchMessageFromChat.Message.OwningUser createOutFetchMessageFromChatMessageOwningUser() {
        return new OutFetchMessageFromChat.Message.OwningUser();
    }

    /**
     * Create an instance of {@link OutListChat.Chat.OwningUser }
     * 
     */
    public OutListChat.Chat.OwningUser createOutListChatChatOwningUser() {
        return new OutListChat.Chat.OwningUser();
    }

}
