/**
 * Copyright � 2015, Thomas Schreiner, thomas1.schreiner@googlemail.com
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * The views and conclusions contained in the software and documentation are those
 * of the authors and should not be interpreted as representing official policies,
 * either expressed or implied, of the FreeBSD Project.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.01 at 07:44:43 PM CEST 
//


package de.radiohacks.frinmeba.modellong;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="Message" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="MessageID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="MessageTyp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="SendTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                     &lt;element name="ReadTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                     &lt;element name="ShowTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                     &lt;element name="OwningUser">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="OwningUserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="OwningUserID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="TextMsgID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="ImageMsgID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="ContactMsgID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="LocationMsgID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="FileMsgID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="VideoMsgID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="OriginMsgID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="NumberTotal" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="NumberRead" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="NumberShow" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *         &lt;element name="Errortext" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "message",
    "errortext"
})
@XmlRootElement(name = "OutFetchMessageFromChat")
public class OutFetchMessageFromChat {

    @XmlElement(name = "Message")
    protected List<OutFetchMessageFromChat.Message> message;
    @XmlElement(name = "Errortext")
    protected String errortext;

    /**
     * Gets the value of the message property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the message property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OutFetchMessageFromChat.Message }
     * 
     * 
     */
    public List<OutFetchMessageFromChat.Message> getMessage() {
        if (message == null) {
            message = new ArrayList<OutFetchMessageFromChat.Message>();
        }
        return this.message;
    }

    /**
     * Gets the value of the errortext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrortext() {
        return errortext;
    }

    /**
     * Sets the value of the errortext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrortext(String value) {
        this.errortext = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MessageID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="MessageTyp" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SendTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="ReadTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="ShowTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="OwningUser">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="OwningUserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="OwningUserID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="TextMsgID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="ImageMsgID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="ContactMsgID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="LocationMsgID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="FileMsgID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="VideoMsgID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="OriginMsgID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="NumberTotal" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="NumberRead" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="NumberShow" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "messageID",
        "messageTyp",
        "sendTimestamp",
        "readTimestamp",
        "showTimestamp",
        "owningUser",
        "textMsgID",
        "imageMsgID",
        "contactMsgID",
        "locationMsgID",
        "fileMsgID",
        "videoMsgID",
        "originMsgID",
        "numberTotal",
        "numberRead",
        "numberShow"
    })
    public static class Message {

        @XmlElement(name = "MessageID")
        protected int messageID;
        @XmlElement(name = "MessageTyp", required = true)
        protected String messageTyp;
        @XmlElement(name = "SendTimestamp")
        protected long sendTimestamp;
        @XmlElement(name = "ReadTimestamp")
        protected long readTimestamp;
        @XmlElement(name = "ShowTimestamp")
        protected long showTimestamp;
        @XmlElement(name = "OwningUser", required = true)
        protected OutFetchMessageFromChat.Message.OwningUser owningUser;
        @XmlElement(name = "TextMsgID")
        protected int textMsgID;
        @XmlElement(name = "ImageMsgID")
        protected int imageMsgID;
        @XmlElement(name = "ContactMsgID")
        protected int contactMsgID;
        @XmlElement(name = "LocationMsgID")
        protected int locationMsgID;
        @XmlElement(name = "FileMsgID")
        protected int fileMsgID;
        @XmlElement(name = "VideoMsgID")
        protected int videoMsgID;
        @XmlElement(name = "OriginMsgID")
        protected int originMsgID;
        @XmlElement(name = "NumberTotal")
        protected int numberTotal;
        @XmlElement(name = "NumberRead")
        protected int numberRead;
        @XmlElement(name = "NumberShow")
        protected int numberShow;

        /**
         * Gets the value of the messageID property.
         * 
         */
        public int getMessageID() {
            return messageID;
        }

        /**
         * Sets the value of the messageID property.
         * 
         */
        public void setMessageID(int value) {
            this.messageID = value;
        }

        /**
         * Gets the value of the messageTyp property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMessageTyp() {
            return messageTyp;
        }

        /**
         * Sets the value of the messageTyp property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMessageTyp(String value) {
            this.messageTyp = value;
        }

        /**
         * Gets the value of the sendTimestamp property.
         * 
         */
        public long getSendTimestamp() {
            return sendTimestamp;
        }

        /**
         * Sets the value of the sendTimestamp property.
         * 
         */
        public void setSendTimestamp(long value) {
            this.sendTimestamp = value;
        }

        /**
         * Gets the value of the readTimestamp property.
         * 
         */
        public long getReadTimestamp() {
            return readTimestamp;
        }

        /**
         * Sets the value of the readTimestamp property.
         * 
         */
        public void setReadTimestamp(long value) {
            this.readTimestamp = value;
        }

        /**
         * Gets the value of the showTimestamp property.
         * 
         */
        public long getShowTimestamp() {
            return showTimestamp;
        }

        /**
         * Sets the value of the showTimestamp property.
         * 
         */
        public void setShowTimestamp(long value) {
            this.showTimestamp = value;
        }

        /**
         * Gets the value of the owningUser property.
         * 
         * @return
         *     possible object is
         *     {@link OutFetchMessageFromChat.Message.OwningUser }
         *     
         */
        public OutFetchMessageFromChat.Message.OwningUser getOwningUser() {
            return owningUser;
        }

        /**
         * Sets the value of the owningUser property.
         * 
         * @param value
         *     allowed object is
         *     {@link OutFetchMessageFromChat.Message.OwningUser }
         *     
         */
        public void setOwningUser(OutFetchMessageFromChat.Message.OwningUser value) {
            this.owningUser = value;
        }

        /**
         * Gets the value of the textMsgID property.
         * 
         */
        public int getTextMsgID() {
            return textMsgID;
        }

        /**
         * Sets the value of the textMsgID property.
         * 
         */
        public void setTextMsgID(int value) {
            this.textMsgID = value;
        }

        /**
         * Gets the value of the imageMsgID property.
         * 
         */
        public int getImageMsgID() {
            return imageMsgID;
        }

        /**
         * Sets the value of the imageMsgID property.
         * 
         */
        public void setImageMsgID(int value) {
            this.imageMsgID = value;
        }

        /**
         * Gets the value of the contactMsgID property.
         * 
         */
        public int getContactMsgID() {
            return contactMsgID;
        }

        /**
         * Sets the value of the contactMsgID property.
         * 
         */
        public void setContactMsgID(int value) {
            this.contactMsgID = value;
        }

        /**
         * Gets the value of the locationMsgID property.
         * 
         */
        public int getLocationMsgID() {
            return locationMsgID;
        }

        /**
         * Sets the value of the locationMsgID property.
         * 
         */
        public void setLocationMsgID(int value) {
            this.locationMsgID = value;
        }

        /**
         * Gets the value of the fileMsgID property.
         * 
         */
        public int getFileMsgID() {
            return fileMsgID;
        }

        /**
         * Sets the value of the fileMsgID property.
         * 
         */
        public void setFileMsgID(int value) {
            this.fileMsgID = value;
        }

        /**
         * Gets the value of the videoMsgID property.
         * 
         */
        public int getVideoMsgID() {
            return videoMsgID;
        }

        /**
         * Sets the value of the videoMsgID property.
         * 
         */
        public void setVideoMsgID(int value) {
            this.videoMsgID = value;
        }

        /**
         * Gets the value of the originMsgID property.
         * 
         */
        public int getOriginMsgID() {
            return originMsgID;
        }

        /**
         * Sets the value of the originMsgID property.
         * 
         */
        public void setOriginMsgID(int value) {
            this.originMsgID = value;
        }

        /**
         * Gets the value of the numberTotal property.
         * 
         */
        public int getNumberTotal() {
            return numberTotal;
        }

        /**
         * Sets the value of the numberTotal property.
         * 
         */
        public void setNumberTotal(int value) {
            this.numberTotal = value;
        }

        /**
         * Gets the value of the numberRead property.
         * 
         */
        public int getNumberRead() {
            return numberRead;
        }

        /**
         * Sets the value of the numberRead property.
         * 
         */
        public void setNumberRead(int value) {
            this.numberRead = value;
        }

        /**
         * Gets the value of the numberShow property.
         * 
         */
        public int getNumberShow() {
            return numberShow;
        }

        /**
         * Sets the value of the numberShow property.
         * 
         */
        public void setNumberShow(int value) {
            this.numberShow = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="OwningUserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="OwningUserID" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "owningUserName",
            "owningUserID"
        })
        public static class OwningUser {

            @XmlElement(name = "OwningUserName", required = true)
            protected String owningUserName;
            @XmlElement(name = "OwningUserID")
            protected int owningUserID;

            /**
             * Gets the value of the owningUserName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOwningUserName() {
                return owningUserName;
            }

            /**
             * Sets the value of the owningUserName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOwningUserName(String value) {
                this.owningUserName = value;
            }

            /**
             * Gets the value of the owningUserID property.
             * 
             */
            public int getOwningUserID() {
                return owningUserID;
            }

            /**
             * Sets the value of the owningUserID property.
             * 
             */
            public void setOwningUserID(int value) {
                this.owningUserID = value;
            }

        }

    }

}
