/**
 * Copyright � 2015, Thomas Schreiner, thomas1.schreiner@googlemail.com
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * The views and conclusions contained in the software and documentation are those
 * of the authors and should not be interpreted as representing official policies,
 * either expressed or implied, of the FreeBSD Project.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.01 at 12:27:25 PM CET 
//


package de.radiohacks.frinmeba.modellong;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="Chat" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="Chatname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="ChatID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="OwningUser">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="OwningUserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="OwningUserID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *         &lt;element name="Errortext" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "chat",
    "errortext"
})
@XmlRootElement(name = "OutListChat")
public class OutListChat {

    @XmlElement(name = "Chat")
    protected List<OutListChat.Chat> chat;
    @XmlElement(name = "Errortext")
    protected String errortext;

    /**
     * Gets the value of the chat property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the chat property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChat().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OutListChat.Chat }
     * 
     * 
     */
    public List<OutListChat.Chat> getChat() {
        if (chat == null) {
            chat = new ArrayList<OutListChat.Chat>();
        }
        return this.chat;
    }

    /**
     * Gets the value of the errortext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrortext() {
        return errortext;
    }

    /**
     * Sets the value of the errortext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrortext(String value) {
        this.errortext = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Chatname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ChatID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="OwningUser">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="OwningUserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="OwningUserID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "chatname",
        "chatID",
        "owningUser"
    })
    public static class Chat {

        @XmlElement(name = "Chatname", required = true)
        protected String chatname;
        @XmlElement(name = "ChatID")
        protected int chatID;
        @XmlElement(name = "OwningUser", required = true)
        protected OutListChat.Chat.OwningUser owningUser;

        /**
         * Gets the value of the chatname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChatname() {
            return chatname;
        }

        /**
         * Sets the value of the chatname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChatname(String value) {
            this.chatname = value;
        }

        /**
         * Gets the value of the chatID property.
         * 
         */
        public int getChatID() {
            return chatID;
        }

        /**
         * Sets the value of the chatID property.
         * 
         */
        public void setChatID(int value) {
            this.chatID = value;
        }

        /**
         * Gets the value of the owningUser property.
         * 
         * @return
         *     possible object is
         *     {@link OutListChat.Chat.OwningUser }
         *     
         */
        public OutListChat.Chat.OwningUser getOwningUser() {
            return owningUser;
        }

        /**
         * Sets the value of the owningUser property.
         * 
         * @param value
         *     allowed object is
         *     {@link OutListChat.Chat.OwningUser }
         *     
         */
        public void setOwningUser(OutListChat.Chat.OwningUser value) {
            this.owningUser = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="OwningUserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="OwningUserID" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "owningUserName",
            "owningUserID"
        })
        public static class OwningUser {

            @XmlElement(name = "OwningUserName", required = true)
            protected String owningUserName;
            @XmlElement(name = "OwningUserID")
            protected int owningUserID;

            /**
             * Gets the value of the owningUserName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOwningUserName() {
                return owningUserName;
            }

            /**
             * Sets the value of the owningUserName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOwningUserName(String value) {
                this.owningUserName = value;
            }

            /**
             * Gets the value of the owningUserID property.
             * 
             */
            public int getOwningUserID() {
                return owningUserID;
            }

            /**
             * Sets the value of the owningUserID property.
             * 
             */
            public void setOwningUserID(int value) {
                this.owningUserID = value;
            }

        }

    }

}
