//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.26 at 08:36:09 PM CET 
//


package de.radiohacks.frinmeba.model.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ImM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ImMD5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "imM",
    "imMD5"
})
@XmlRootElement(name = "ISImM")
public class ISImM {

    @XmlElement(name = "ImM", required = true)
    protected String imM;
    @XmlElement(name = "ImMD5", required = true)
    protected String imMD5;

    /**
     * Gets the value of the imM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImM() {
        return imM;
    }

    /**
     * Sets the value of the imM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImM(String value) {
        this.imM = value;
    }

    /**
     * Gets the value of the imMD5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImMD5() {
        return imMD5;
    }

    /**
     * Sets the value of the imMD5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImMD5(String value) {
        this.imMD5 = value;
    }

}
