//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.26 at 08:36:09 PM CET 
//


package de.radiohacks.frinmeba.model.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.radiohacks.frinmeba.model.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.radiohacks.frinmeba.model.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OICIc }
     * 
     */
    public OICIc createOICIc() {
        return new OICIc();
    }

    /**
     * Create an instance of {@link IDMFC }
     * 
     */
    public IDMFC createIDMFC() {
        return new IDMFC();
    }

    /**
     * Create an instance of {@link ISU }
     * 
     */
    public ISU createISU() {
        return new ISU();
    }

    /**
     * Create an instance of {@link OGViMMD }
     * 
     */
    public OGViMMD createOGViMMD() {
        return new OGViMMD();
    }

    /**
     * Create an instance of {@link OCN }
     * 
     */
    public OCN createOCN() {
        return new OCN();
    }

    /**
     * Create an instance of {@link C }
     * 
     */
    public C createC() {
        return new C();
    }

    /**
     * Create an instance of {@link OU }
     * 
     */
    public OU createOU() {
        return new OU();
    }

    /**
     * Create an instance of {@link CNM }
     * 
     */
    public CNM createCNM() {
        return new CNM();
    }

    /**
     * Create an instance of {@link IGImM }
     * 
     */
    public IGImM createIGImM() {
        return new IGImM();
    }

    /**
     * Create an instance of {@link OGImM }
     * 
     */
    public OGImM createOGImM() {
        return new OGImM();
    }

    /**
     * Create an instance of {@link OGImMMD }
     * 
     */
    public OGImMMD createOGImMMD() {
        return new OGImMMD();
    }

    /**
     * Create an instance of {@link IGMI }
     * 
     */
    public IGMI createIGMI() {
        return new IGMI();
    }

    /**
     * Create an instance of {@link OSViM }
     * 
     */
    public OSViM createOSViM() {
        return new OSViM();
    }

    /**
     * Create an instance of {@link ISShT }
     * 
     */
    public ISShT createISShT() {
        return new ISShT();
    }

    /**
     * Create an instance of {@link OLiCh }
     * 
     */
    public OLiCh createOLiCh() {
        return new OLiCh();
    }

    /**
     * Create an instance of {@link OSTeM }
     * 
     */
    public OSTeM createOSTeM() {
        return new OSTeM();
    }

    /**
     * Create an instance of {@link OAckCD }
     * 
     */
    public OAckCD createOAckCD() {
        return new OAckCD();
    }

    /**
     * Create an instance of {@link ISFiM }
     * 
     */
    public ISFiM createISFiM() {
        return new ISFiM();
    }

    /**
     * Create an instance of {@link MI }
     * 
     */
    public MI createMI() {
        return new MI();
    }

    /**
     * Create an instance of {@link OIMIC }
     * 
     */
    public OIMIC createOIMIC() {
        return new OIMIC();
    }

    /**
     * Create an instance of {@link IFMFC }
     * 
     */
    public IFMFC createIFMFC() {
        return new IFMFC();
    }

    /**
     * Create an instance of {@link IGViMMD }
     * 
     */
    public IGViMMD createIGViMMD() {
        return new IGViMMD();
    }

    /**
     * Create an instance of {@link IAdUC }
     * 
     */
    public IAdUC createIAdUC() {
        return new IAdUC();
    }

    /**
     * Create an instance of {@link ODeCh }
     * 
     */
    public ODeCh createODeCh() {
        return new ODeCh();
    }

    /**
     * Create an instance of {@link ISCoM }
     * 
     */
    public ISCoM createISCoM() {
        return new ISCoM();
    }

    /**
     * Create an instance of {@link OSIcM }
     * 
     */
    public OSIcM createOSIcM() {
        return new OSIcM();
    }

    /**
     * Create an instance of {@link IICIc }
     * 
     */
    public IICIc createIICIc() {
        return new IICIc();
    }

    /**
     * Create an instance of {@link OAckMD }
     * 
     */
    public OAckMD createOAckMD() {
        return new OAckMD();
    }

    /**
     * Create an instance of {@link OAdUC }
     * 
     */
    public OAdUC createOAdUC() {
        return new OAdUC();
    }

    /**
     * Create an instance of {@link ShT }
     * 
     */
    public ShT createShT() {
        return new ShT();
    }

    /**
     * Create an instance of {@link OSU }
     * 
     */
    public OSU createOSU() {
        return new OSU();
    }

    /**
     * Create an instance of {@link U }
     * 
     */
    public U createU() {
        return new U();
    }

    /**
     * Create an instance of {@link ISTeM }
     * 
     */
    public ISTeM createISTeM() {
        return new ISTeM();
    }

    /**
     * Create an instance of {@link IGFiM }
     * 
     */
    public IGFiM createIGFiM() {
        return new IGFiM();
    }

    /**
     * Create an instance of {@link IGImMMD }
     * 
     */
    public IGImMMD createIGImMMD() {
        return new IGImMMD();
    }

    /**
     * Create an instance of {@link IGLoM }
     * 
     */
    public IGLoM createIGLoM() {
        return new IGLoM();
    }

    /**
     * Create an instance of {@link ISImM }
     * 
     */
    public ISImM createISImM() {
        return new ISImM();
    }

    /**
     * Create an instance of {@link IReUC }
     * 
     */
    public IReUC createIReUC() {
        return new IReUC();
    }

    /**
     * Create an instance of {@link OGMI }
     * 
     */
    public OGMI createOGMI() {
        return new OGMI();
    }

    /**
     * Create an instance of {@link MIB }
     * 
     */
    public MIB createMIB() {
        return new MIB();
    }

    /**
     * Create an instance of {@link OFMFC }
     * 
     */
    public OFMFC createOFMFC() {
        return new OFMFC();
    }

    /**
     * Create an instance of {@link M }
     * 
     */
    public M createM() {
        return new M();
    }

    /**
     * Create an instance of {@link ISViM }
     * 
     */
    public ISViM createISViM() {
        return new ISViM();
    }

    /**
     * Create an instance of {@link IAckMD }
     * 
     */
    public IAckMD createIAckMD() {
        return new IAckMD();
    }

    /**
     * Create an instance of {@link IAckCD }
     * 
     */
    public IAckCD createIAckCD() {
        return new IAckCD();
    }

    /**
     * Create an instance of {@link OSShT }
     * 
     */
    public OSShT createOSShT() {
        return new OSShT();
    }

    /**
     * Create an instance of {@link OSCoM }
     * 
     */
    public OSCoM createOSCoM() {
        return new OSCoM();
    }

    /**
     * Create an instance of {@link OGViM }
     * 
     */
    public OGViM createOGViM() {
        return new OGViM();
    }

    /**
     * Create an instance of {@link OIUIc }
     * 
     */
    public OIUIc createOIUIc() {
        return new OIUIc();
    }

    /**
     * Create an instance of {@link OGCoM }
     * 
     */
    public OGCoM createOGCoM() {
        return new OGCoM();
    }

    /**
     * Create an instance of {@link OLiUs }
     * 
     */
    public OLiUs createOLiUs() {
        return new OLiUs();
    }

    /**
     * Create an instance of {@link IDeCh }
     * 
     */
    public IDeCh createIDeCh() {
        return new IDeCh();
    }

    /**
     * Create an instance of {@link OSFiM }
     * 
     */
    public OSFiM createOSFiM() {
        return new OSFiM();
    }

    /**
     * Create an instance of {@link IGCoM }
     * 
     */
    public IGCoM createIGCoM() {
        return new IGCoM();
    }

    /**
     * Create an instance of {@link IIMIC }
     * 
     */
    public IIMIC createIIMIC() {
        return new IIMIC();
    }

    /**
     * Create an instance of {@link ISLoM }
     * 
     */
    public ISLoM createISLoM() {
        return new ISLoM();
    }

    /**
     * Create an instance of {@link IGFiMMD }
     * 
     */
    public IGFiMMD createIGFiMMD() {
        return new IGFiMMD();
    }

    /**
     * Create an instance of {@link IIUIc }
     * 
     */
    public IIUIc createIIUIc() {
        return new IIUIc();
    }

    /**
     * Create an instance of {@link ICrCh }
     * 
     */
    public ICrCh createICrCh() {
        return new ICrCh();
    }

    /**
     * Create an instance of {@link OSLoM }
     * 
     */
    public OSLoM createOSLoM() {
        return new OSLoM();
    }

    /**
     * Create an instance of {@link IGTeM }
     * 
     */
    public IGTeM createIGTeM() {
        return new IGTeM();
    }

    /**
     * Create an instance of {@link OGFiMMD }
     * 
     */
    public OGFiMMD createOGFiMMD() {
        return new OGFiMMD();
    }

    /**
     * Create an instance of {@link ISiUp }
     * 
     */
    public ISiUp createISiUp() {
        return new ISiUp();
    }

    /**
     * Create an instance of {@link ILiUs }
     * 
     */
    public ILiUs createILiUs() {
        return new ILiUs();
    }

    /**
     * Create an instance of {@link OGLoM }
     * 
     */
    public OGLoM createOGLoM() {
        return new OGLoM();
    }

    /**
     * Create an instance of {@link ISIcM }
     * 
     */
    public ISIcM createISIcM() {
        return new ISIcM();
    }

    /**
     * Create an instance of {@link ODMFC }
     * 
     */
    public ODMFC createODMFC() {
        return new ODMFC();
    }

    /**
     * Create an instance of {@link IGViM }
     * 
     */
    public IGViM createIGViM() {
        return new IGViM();
    }

    /**
     * Create an instance of {@link OGTeM }
     * 
     */
    public OGTeM createOGTeM() {
        return new OGTeM();
    }

    /**
     * Create an instance of {@link OCrCh }
     * 
     */
    public OCrCh createOCrCh() {
        return new OCrCh();
    }

    /**
     * Create an instance of {@link OGFiM }
     * 
     */
    public OGFiM createOGFiM() {
        return new OGFiM();
    }

    /**
     * Create an instance of {@link OReUC }
     * 
     */
    public OReUC createOReUC() {
        return new OReUC();
    }

    /**
     * Create an instance of {@link OSiUp }
     * 
     */
    public OSiUp createOSiUp() {
        return new OSiUp();
    }

    /**
     * Create an instance of {@link OSImM }
     * 
     */
    public OSImM createOSImM() {
        return new OSImM();
    }

}
