//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.26 at 08:36:09 PM CET 
//


package de.radiohacks.frinmeba.model.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OUN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OUID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "oun",
    "ouid"
})
@XmlRootElement(name = "OU")
public class OU {

    @XmlElement(name = "OUN", required = true)
    protected String oun;
    @XmlElement(name = "OUID")
    protected int ouid;

    /**
     * Gets the value of the oun property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOUN() {
        return oun;
    }

    /**
     * Sets the value of the oun property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOUN(String value) {
        this.oun = value;
    }

    /**
     * Gets the value of the ouid property.
     * 
     */
    public int getOUID() {
        return ouid;
    }

    /**
     * Sets the value of the ouid property.
     * 
     */
    public void setOUID(int value) {
        this.ouid = value;
    }

}
