//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.30 at 08:04:57 PM CEST 
//


package de.radiohacks.frinmeba.modelshort;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="User" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="UN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="UID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="E" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *         &lt;element name="ET" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "user",
    "et"
})
@XmlRootElement(name = "OLiUs")
public class OLiUs {

    @XmlElement(name = "User")
    protected List<OLiUs.User> user;
    @XmlElement(name = "ET")
    protected String et;

    /**
     * Gets the value of the user property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the user property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUser().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OLiUs.User }
     * 
     * 
     */
    public List<OLiUs.User> getUser() {
        if (user == null) {
            user = new ArrayList<OLiUs.User>();
        }
        return this.user;
    }

    /**
     * Gets the value of the et property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getET() {
        return et;
    }

    /**
     * Sets the value of the et property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setET(String value) {
        this.et = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="UN" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="UID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="E" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "un",
        "uid",
        "e"
    })
    public static class User {

        @XmlElement(name = "UN", required = true)
        protected String un;
        @XmlElement(name = "UID")
        protected int uid;
        @XmlElement(name = "E", required = true)
        protected String e;

        /**
         * Gets the value of the un property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUN() {
            return un;
        }

        /**
         * Sets the value of the un property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUN(String value) {
            this.un = value;
        }

        /**
         * Gets the value of the uid property.
         * 
         */
        public int getUID() {
            return uid;
        }

        /**
         * Sets the value of the uid property.
         * 
         */
        public void setUID(int value) {
            this.uid = value;
        }

        /**
         * Gets the value of the e property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getE() {
            return e;
        }

        /**
         * Sets the value of the e property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setE(String value) {
            this.e = value;
        }

    }

}
