package de.radiohacks.frinmeba.model.hibernate;
// Generated 27.01.2018 21:05:17 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * FrinmeDbChats generated by hbm2java
 */
public class FrinmeDbChats implements java.io.Serializable {
    
    /**
     * 
     */
    private static final long serialVersionUID = 5583665864427668655L;
    private Integer id;
    private FrinmeDbImage frinmeDbImage;
    private FrinmeDbUsers frinmeDbUsers;
    private String chatname;
    private Set<?> frinmeDbUserToChatses = new HashSet<Object>(0);
    
    public FrinmeDbChats() {
    }
    
    public FrinmeDbChats(FrinmeDbUsers frinmeDbUsers, String chatname) {
        this.frinmeDbUsers = frinmeDbUsers;
        this.chatname = chatname;
    }
    
    public FrinmeDbChats(FrinmeDbImage frinmeDbImage,
            FrinmeDbUsers frinmeDbUsers, String chatname,
            Set<?> frinmeDbUserToChatses) {
        this.frinmeDbImage = frinmeDbImage;
        this.frinmeDbUsers = frinmeDbUsers;
        this.chatname = chatname;
        this.frinmeDbUserToChatses = frinmeDbUserToChatses;
    }
    
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    public FrinmeDbImage getFrinmeDbImage() {
        return this.frinmeDbImage;
    }
    
    public void setFrinmeDbImage(FrinmeDbImage frinmeDbImage) {
        this.frinmeDbImage = frinmeDbImage;
    }
    
    public FrinmeDbUsers getFrinmeDbUsers() {
        return this.frinmeDbUsers;
    }
    
    public void setFrinmeDbUsers(FrinmeDbUsers frinmeDbUsers) {
        this.frinmeDbUsers = frinmeDbUsers;
    }
    
    public String getChatname() {
        return this.chatname;
    }
    
    public void setChatname(String chatname) {
        this.chatname = chatname;
    }
    
    public Set<?> getFrinmeDbUserToChatses() {
        return this.frinmeDbUserToChatses;
    }
    
    public void setFrinmeDbUserToChatses(Set<?> frinmeDbUserToChatses) {
        this.frinmeDbUserToChatses = frinmeDbUserToChatses;
    }
    
}
