package de.radiohacks.frinmeba.model.hibernate;
// Generated 27.01.2018 21:05:17 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * FrinmeDbUsers generated by hbm2java
 */
public class FrinmeDbUsers implements java.io.Serializable {
    
    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer id;
    private FrinmeDbImage frinmeDbImage;
    private String username;
    private String b64username;
    private String password;
    private String email;
    private long signupDate;
    private Byte status;
    private long authenticationTime;
    private boolean active;
    private Set<?> frinmeDbUserToChatses = new HashSet<Object>(0);
    private Set<?> frinmeDbChatses = new HashSet<Object>(0);
    private Set<?> frinmeDbMessageses = new HashSet<Object>(0);
    
    public FrinmeDbUsers() {
    }
    
    public FrinmeDbUsers(String username, String b64username, String password,
            String email, long signupDate, long authenticationTime,
            boolean active) {
        this.username = username;
        this.b64username = b64username;
        this.password = password;
        this.email = email;
        this.signupDate = signupDate;
        this.authenticationTime = authenticationTime;
        this.active = active;
    }
    
    public FrinmeDbUsers(FrinmeDbImage frinmeDbImage, String username,
            String b64username, String password, String email, long signupDate,
            Byte status, long authenticationTime, boolean active,
            Set<?> frinmeDbUserToChatses, Set<?> frinmeDbChatses,
            Set<?> frinmeDbMessageses) {
        this.frinmeDbImage = frinmeDbImage;
        this.username = username;
        this.b64username = b64username;
        this.password = password;
        this.email = email;
        this.signupDate = signupDate;
        this.status = status;
        this.authenticationTime = authenticationTime;
        this.active = active;
        this.frinmeDbUserToChatses = frinmeDbUserToChatses;
        this.frinmeDbChatses = frinmeDbChatses;
        this.frinmeDbMessageses = frinmeDbMessageses;
    }
    
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    public FrinmeDbImage getFrinmeDbImage() {
        return this.frinmeDbImage;
    }
    
    public void setFrinmeDbImage(FrinmeDbImage frinmeDbImage) {
        this.frinmeDbImage = frinmeDbImage;
    }
    
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    public String getB64username() {
        return this.b64username;
    }
    
    public void setB64username(String b64username) {
        this.b64username = b64username;
    }
    
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    public long getSignupDate() {
        return this.signupDate;
    }
    
    public void setSignupDate(long signupDate) {
        this.signupDate = signupDate;
    }
    
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    
    public long getAuthenticationTime() {
        return this.authenticationTime;
    }
    
    public void setAuthenticationTime(long authenticationTime) {
        this.authenticationTime = authenticationTime;
    }
    
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    
    public Set<?> getFrinmeDbUserToChatses() {
        return this.frinmeDbUserToChatses;
    }
    
    public void setFrinmeDbUserToChatses(Set<?> frinmeDbUserToChatses) {
        this.frinmeDbUserToChatses = frinmeDbUserToChatses;
    }
    
    public Set<?> getFrinmeDbChatses() {
        return this.frinmeDbChatses;
    }
    
    public void setFrinmeDbChatses(Set<?> frinmeDbChatses) {
        this.frinmeDbChatses = frinmeDbChatses;
    }
    
    public Set<?> getFrinmeDbMessageses() {
        return this.frinmeDbMessageses;
    }
    
    public void setFrinmeDbMessageses(Set<?> frinmeDbMessageses) {
        this.frinmeDbMessageses = frinmeDbMessageses;
    }
    
}
