package de.radiohacks.frinmeba.model.hibernate;
// Generated 27.01.2018 21:05:17 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * FrinmeDbUserToChats generated by hbm2java
 */
public class FrinmeDbUserToChats implements java.io.Serializable {
    
    /**
     * 
     */
    private static final long serialVersionUID = 737989810814530942L;
    private Integer id;
    private FrinmeDbUsers frinmeDbUsers;
    private FrinmeDbChats frinmeDbChats;
    private long readTimestamp;
    private long tempReadTimestamp;
    private Set<?> frinmeDbMessageses = new HashSet<Object>(0);
    
    public FrinmeDbUserToChats() {
    }
    
    public FrinmeDbUserToChats(FrinmeDbUsers frinmeDbUsers,
            FrinmeDbChats frinmeDbChats, long readTimestamp,
            long tempReadTimestamp) {
        this.frinmeDbUsers = frinmeDbUsers;
        this.frinmeDbChats = frinmeDbChats;
        this.readTimestamp = readTimestamp;
        this.tempReadTimestamp = tempReadTimestamp;
    }
    
    public FrinmeDbUserToChats(FrinmeDbUsers frinmeDbUsers,
            FrinmeDbChats frinmeDbChats, long readTimestamp,
            long tempReadTimestamp, Set<?> frinmeDbMessageses) {
        this.frinmeDbUsers = frinmeDbUsers;
        this.frinmeDbChats = frinmeDbChats;
        this.readTimestamp = readTimestamp;
        this.tempReadTimestamp = tempReadTimestamp;
        this.frinmeDbMessageses = frinmeDbMessageses;
    }
    
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    public FrinmeDbUsers getFrinmeDbUsers() {
        return this.frinmeDbUsers;
    }
    
    public void setFrinmeDbUsers(FrinmeDbUsers frinmeDbUsers) {
        this.frinmeDbUsers = frinmeDbUsers;
    }
    
    public FrinmeDbChats getFrinmeDbChats() {
        return this.frinmeDbChats;
    }
    
    public void setFrinmeDbChats(FrinmeDbChats frinmeDbChats) {
        this.frinmeDbChats = frinmeDbChats;
    }
    
    public long getReadTimestamp() {
        return this.readTimestamp;
    }
    
    public void setReadTimestamp(long readTimestamp) {
        this.readTimestamp = readTimestamp;
    }
    
    public long getTempReadTimestamp() {
        return this.tempReadTimestamp;
    }
    
    public void setTempReadTimestamp(long tempReadTimestamp) {
        this.tempReadTimestamp = tempReadTimestamp;
    }
    
    public Set<?> getFrinmeDbMessageses() {
        return this.frinmeDbMessageses;
    }
    
    public void setFrinmeDbMessageses(Set<?> frinmeDbMessageses) {
        this.frinmeDbMessageses = frinmeDbMessageses;
    }
    
}
