package de.radiohacks.frinmeba.model.hibernate;
// Generated 27.01.2018 21:05:17 by Hibernate Tools 4.0.0

/**
 * FrinmeDbMessages generated by hbm2java
 */
public class FrinmeDbMessages implements java.io.Serializable {
    
    /**
     * 
     */
    private static final long serialVersionUID = 1292728380323177834L;
    private Integer id;
    private FrinmeDbUserToChats frinmeDbUserToChats;
    private FrinmeDbText frinmeDbText;
    private FrinmeDbContact frinmeDbContact;
    private FrinmeDbFile frinmeDbFile;
    private FrinmeDbVideo frinmeDbVideo;
    private FrinmeDbLocation frinmeDbLocation;
    private FrinmeDbImage frinmeDbImage;
    private FrinmeDbUsers frinmeDbUsers;
    private String messageTyp;
    private long sendTimestamp;
    private long readTimestamp;
    private long tempReadTimestamp;
    private long showTimestamp;
    private Integer originMsgId;
    
    public FrinmeDbMessages() {
    }
    
    public FrinmeDbMessages(FrinmeDbUserToChats frinmeDbUserToChats,
            FrinmeDbUsers frinmeDbUsers, String messageTyp, long sendTimestamp,
            long readTimestamp, long tempReadTimestamp, long showTimestamp) {
        this.frinmeDbUserToChats = frinmeDbUserToChats;
        this.frinmeDbUsers = frinmeDbUsers;
        this.messageTyp = messageTyp;
        this.sendTimestamp = sendTimestamp;
        this.readTimestamp = readTimestamp;
        this.tempReadTimestamp = tempReadTimestamp;
        this.showTimestamp = showTimestamp;
    }
    
    public FrinmeDbMessages(FrinmeDbUserToChats frinmeDbUserToChats,
            FrinmeDbText frinmeDbText, FrinmeDbContact frinmeDbContact,
            FrinmeDbFile frinmeDbFile, FrinmeDbVideo frinmeDbVideo,
            FrinmeDbLocation frinmeDbLocation, FrinmeDbImage frinmeDbImage,
            FrinmeDbUsers frinmeDbUsers, String messageTyp, long sendTimestamp,
            long readTimestamp, long tempReadTimestamp, long showTimestamp,
            Integer originMsgId) {
        this.frinmeDbUserToChats = frinmeDbUserToChats;
        this.frinmeDbText = frinmeDbText;
        this.frinmeDbContact = frinmeDbContact;
        this.frinmeDbFile = frinmeDbFile;
        this.frinmeDbVideo = frinmeDbVideo;
        this.frinmeDbLocation = frinmeDbLocation;
        this.frinmeDbImage = frinmeDbImage;
        this.frinmeDbUsers = frinmeDbUsers;
        this.messageTyp = messageTyp;
        this.sendTimestamp = sendTimestamp;
        this.readTimestamp = readTimestamp;
        this.tempReadTimestamp = tempReadTimestamp;
        this.showTimestamp = showTimestamp;
        this.originMsgId = originMsgId;
    }
    
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    public FrinmeDbUserToChats getFrinmeDbUserToChats() {
        return this.frinmeDbUserToChats;
    }
    
    public void setFrinmeDbUserToChats(
            FrinmeDbUserToChats frinmeDbUserToChats) {
        this.frinmeDbUserToChats = frinmeDbUserToChats;
    }
    
    public FrinmeDbText getFrinmeDbText() {
        return this.frinmeDbText;
    }
    
    public void setFrinmeDbText(FrinmeDbText frinmeDbText) {
        this.frinmeDbText = frinmeDbText;
    }
    
    public FrinmeDbContact getFrinmeDbContact() {
        return this.frinmeDbContact;
    }
    
    public void setFrinmeDbContact(FrinmeDbContact frinmeDbContact) {
        this.frinmeDbContact = frinmeDbContact;
    }
    
    public FrinmeDbFile getFrinmeDbFile() {
        return this.frinmeDbFile;
    }
    
    public void setFrinmeDbFile(FrinmeDbFile frinmeDbFile) {
        this.frinmeDbFile = frinmeDbFile;
    }
    
    public FrinmeDbVideo getFrinmeDbVideo() {
        return this.frinmeDbVideo;
    }
    
    public void setFrinmeDbVideo(FrinmeDbVideo frinmeDbVideo) {
        this.frinmeDbVideo = frinmeDbVideo;
    }
    
    public FrinmeDbLocation getFrinmeDbLocation() {
        return this.frinmeDbLocation;
    }
    
    public void setFrinmeDbLocation(FrinmeDbLocation frinmeDbLocation) {
        this.frinmeDbLocation = frinmeDbLocation;
    }
    
    public FrinmeDbImage getFrinmeDbImage() {
        return this.frinmeDbImage;
    }
    
    public void setFrinmeDbImage(FrinmeDbImage frinmeDbImage) {
        this.frinmeDbImage = frinmeDbImage;
    }
    
    public FrinmeDbUsers getFrinmeDbUsers() {
        return this.frinmeDbUsers;
    }
    
    public void setFrinmeDbUsers(FrinmeDbUsers frinmeDbUsers) {
        this.frinmeDbUsers = frinmeDbUsers;
    }
    
    public String getMessageTyp() {
        return this.messageTyp;
    }
    
    public void setMessageTyp(String messageTyp) {
        this.messageTyp = messageTyp;
    }
    
    public long getSendTimestamp() {
        return this.sendTimestamp;
    }
    
    public void setSendTimestamp(long sendTimestamp) {
        this.sendTimestamp = sendTimestamp;
    }
    
    public long getReadTimestamp() {
        return this.readTimestamp;
    }
    
    public void setReadTimestamp(long readTimestamp) {
        this.readTimestamp = readTimestamp;
    }
    
    public long getTempReadTimestamp() {
        return this.tempReadTimestamp;
    }
    
    public void setTempReadTimestamp(long tempReadTimestamp) {
        this.tempReadTimestamp = tempReadTimestamp;
    }
    
    public long getShowTimestamp() {
        return this.showTimestamp;
    }
    
    public void setShowTimestamp(long showTimestamp) {
        this.showTimestamp = showTimestamp;
    }
    
    public Integer getOriginMsgId() {
        return this.originMsgId;
    }
    
    public void setOriginMsgId(Integer originMsgId) {
        this.originMsgId = originMsgId;
    }
    
}
