package de.radiohacks.frinmeba.model.hibernate;
// Generated 27.01.2018 21:05:17 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * FrinmeDbVideo generated by hbm2java
 */
public class FrinmeDbVideo implements java.io.Serializable {
    
    /**
     * 
     */
    private static final long serialVersionUID = 8418946666246148878L;
    private Integer id;
    private String video;
    private String md5sum;
    private Set<?> frinmeDbMessageses = new HashSet<Object>(0);
    
    public FrinmeDbVideo() {
    }
    
    public FrinmeDbVideo(String video, String md5sum) {
        this.video = video;
        this.md5sum = md5sum;
    }
    
    public FrinmeDbVideo(String video, String md5sum,
            Set<?> frinmeDbMessageses) {
        this.video = video;
        this.md5sum = md5sum;
        this.frinmeDbMessageses = frinmeDbMessageses;
    }
    
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    public String getVideo() {
        return this.video;
    }
    
    public void setVideo(String video) {
        this.video = video;
    }
    
    public String getMd5sum() {
        return this.md5sum;
    }
    
    public void setMd5sum(String md5sum) {
        this.md5sum = md5sum;
    }
    
    public Set<?> getFrinmeDbMessageses() {
        return this.frinmeDbMessageses;
    }
    
    public void setFrinmeDbMessageses(Set<?> frinmeDbMessageses) {
        this.frinmeDbMessageses = frinmeDbMessageses;
    }
    
}
