package de.radiohacks.frinmeba.model.hibernate;
// Generated 27.01.2018 21:05:17 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * FrinmeDbFile generated by hbm2java
 */
public class FrinmeDbFile implements java.io.Serializable {
    
    /**
     * 
     */
    private static final long serialVersionUID = -1640325693308814128L;
    private Integer id;
    private String file;
    private String md5sum;
    private Set<?> frinmeDbMessageses = new HashSet<Object>(0);
    
    public FrinmeDbFile() {
    }
    
    public FrinmeDbFile(String file, String md5sum) {
        this.file = file;
        this.md5sum = md5sum;
    }
    
    public FrinmeDbFile(String file, String md5sum, Set<?> frinmeDbMessageses) {
        this.file = file;
        this.md5sum = md5sum;
        this.frinmeDbMessageses = frinmeDbMessageses;
    }
    
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    public String getFile() {
        return this.file;
    }
    
    public void setFile(String file) {
        this.file = file;
    }
    
    public String getMd5sum() {
        return this.md5sum;
    }
    
    public void setMd5sum(String md5sum) {
        this.md5sum = md5sum;
    }
    
    public Set<?> getFrinmeDbMessageses() {
        return this.frinmeDbMessageses;
    }
    
    public void setFrinmeDbMessageses(Set<?> frinmeDbMessageses) {
        this.frinmeDbMessageses = frinmeDbMessageses;
    }
    
}
