package de.radiohacks.frinmeba.model.hibernate;
// Generated 27.01.2018 21:05:17 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * FrinmeDbText generated by hbm2java
 */
public class FrinmeDbText implements java.io.Serializable {
    
    /**
     * 
     */
    private static final long serialVersionUID = 3368867053844001737L;
    private Integer id;
    private String text;
    private Set<?> frinmeDbMessageses = new HashSet<Object>(0);
    
    public FrinmeDbText() {
    }
    
    public FrinmeDbText(String text) {
        this.text = text;
    }
    
    public FrinmeDbText(String text, Set<?> frinmeDbMessageses) {
        this.text = text;
        this.frinmeDbMessageses = frinmeDbMessageses;
    }
    
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    
    public Set<?> getFrinmeDbMessageses() {
        return this.frinmeDbMessageses;
    }
    
    public void setFrinmeDbMessageses(Set<?> frinmeDbMessageses) {
        this.frinmeDbMessageses = frinmeDbMessageses;
    }
    
}
