package de.radiohacks.frinmeba.model.hibernate;
// Generated 27.01.2018 21:05:17 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * FrinmeDbLocation generated by hbm2java
 */
public class FrinmeDbLocation implements java.io.Serializable {
    
    /**
     * 
     */
    private static final long serialVersionUID = -5977037136485976608L;
    private Integer id;
    private String location;
    private Set<?> frinmeDbMessageses = new HashSet<Object>(0);
    
    public FrinmeDbLocation() {
    }
    
    public FrinmeDbLocation(String location) {
        this.location = location;
    }
    
    public FrinmeDbLocation(String location, Set<?> frinmeDbMessageses) {
        this.location = location;
        this.frinmeDbMessageses = frinmeDbMessageses;
    }
    
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    
    public Set<?> getFrinmeDbMessageses() {
        return this.frinmeDbMessageses;
    }
    
    public void setFrinmeDbMessageses(Set<?> frinmeDbMessageses) {
        this.frinmeDbMessageses = frinmeDbMessageses;
    }
    
}
