package de.radiohacks.frinmeba.model.hibernate;
// Generated 27.01.2018 21:05:17 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * FrinmeDbImage generated by hbm2java
 */
public class FrinmeDbImage implements java.io.Serializable {
    
    /**
     * 
     */
    private static final long serialVersionUID = -6337645987915012418L;
    private Integer id;
    private String image;
    private String md5sum;
    private Set<?> frinmeDbChatses = new HashSet<Object>(0);
    private Set<?> frinmeDbMessageses = new HashSet<Object>(0);
    private Set<?> frinmeDbUserses = new HashSet<Object>(0);
    
    public FrinmeDbImage() {
    }
    
    public FrinmeDbImage(String image, String md5sum) {
        this.image = image;
        this.md5sum = md5sum;
    }
    
    public FrinmeDbImage(String image, String md5sum, Set<?> frinmeDbChatses,
            Set<?> frinmeDbMessageses, Set<?> frinmeDbUserses) {
        this.image = image;
        this.md5sum = md5sum;
        this.frinmeDbChatses = frinmeDbChatses;
        this.frinmeDbMessageses = frinmeDbMessageses;
        this.frinmeDbUserses = frinmeDbUserses;
    }
    
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    
    public String getMd5sum() {
        return this.md5sum;
    }
    
    public void setMd5sum(String md5sum) {
        this.md5sum = md5sum;
    }
    
    public Set<?> getFrinmeDbChatses() {
        return this.frinmeDbChatses;
    }
    
    public void setFrinmeDbChatses(Set<?> frinmeDbChatses) {
        this.frinmeDbChatses = frinmeDbChatses;
    }
    
    public Set<?> getFrinmeDbMessageses() {
        return this.frinmeDbMessageses;
    }
    
    public void setFrinmeDbMessageses(Set<?> frinmeDbMessageses) {
        this.frinmeDbMessageses = frinmeDbMessageses;
    }
    
    public Set<?> getFrinmeDbUserses() {
        return this.frinmeDbUserses;
    }
    
    public void setFrinmeDbUserses(Set<?> frinmeDbUserses) {
        this.frinmeDbUserses = frinmeDbUserses;
    }
    
}
