package de.radiohacks.frinmeba.model.hibernate;
// Generated 27.01.2018 21:05:17 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * FrinmeDbContact generated by hbm2java
 */
public class FrinmeDbContact implements java.io.Serializable {
    
    /**
     * 
     */
    private static final long serialVersionUID = 5059107128724662710L;
    private Integer id;
    private String contact;
    private Set<?> frinmeDbMessageses = new HashSet<Object>(0);
    
    public FrinmeDbContact() {
    }
    
    public FrinmeDbContact(String contact) {
        this.contact = contact;
    }
    
    public FrinmeDbContact(String contact, Set<?> frinmeDbMessageses) {
        this.contact = contact;
        this.frinmeDbMessageses = frinmeDbMessageses;
    }
    
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    
    public Set<?> getFrinmeDbMessageses() {
        return this.frinmeDbMessageses;
    }
    
    public void setFrinmeDbMessageses(Set<?> frinmeDbMessageses) {
        this.frinmeDbMessageses = frinmeDbMessageses;
    }
    
}
